---
- name: Configure Redis Cluster
  hosts: redis
  gather_facts: no
   vars:
    redis_port: 6379
    # Redis 노드 주소를 포맷하여 하나의 문자열로 생성
    combined_redis_addresses: "{{ groups['redis'] | map('regex_replace', '^(.*)$', '\\1:' + redis_port | string) | join(' ') }}"

  tasks:
    #Reset Clustering
    - name: Restart All Node
      command: sudo systemctl restart redis

    - name: Flush all data from Redis
      command: redis-cli -h {{ ansible_host }} -p 6379 FLUSHALL && redis-cli -h {{ ansible_host }} -p 6379 FLUSHDB && redis-cli -h {{ ansible_host }} -p 6379 CLUSTER RESET
      register: reset_result
      ignore_errors: yes  # 오류가 발생해도 계속 진행하도록 설정
      
    - name: Show flush result
      debug:
        var: reset_result.stdout

    - name: Show combined Redis node addresses
      debug:
        msg: "{{ combined_redis_addresses }}"

    - name: Create Redis cluster
      command: >
        redis-cli --cluster create {{ combined_redis_addresses }} --cluster-yes --cluster-replicas 1
      when: inventory_hostname == groups['redis'][0]  # 첫 번째 마스터 노드에서 클러스터를 생성
      register: cluster_result

    - name: Show cluster creation result
      debug:
        var: cluster_result.stdout
      when: inventory_hostname == groups['redis'][0]
