---
- name: Install Redis from source
  hosts: redis
  become: yes
  vars:
    redis_stack_version: "X.X.X-vXX"
    redis_user: "qubit"
    redis_group: "qubit"
    redis_config_path: "/etc/redis/"
    proxy: "http://172.16.10.20:3128/"
    sysctl_settings:
      - { key: 'fs.file-max', value: '2097152' }
      - { key: 'net.ipv4.ip_local_port_range', value: '1024 65500' }
      - { key: 'net.core.rmem_default', value: '26214400' }
      - { key: 'net.core.rmem_max', value: '26214400' }
      - { key: 'net.core.wmem_default', value: '262144' }
      - { key: 'net.core.wmem_max', value: '1048576' }
      - { key: 'vm.overcommit_memory', value: '1' }

  tasks:
    - name: Stop and disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Install necessary dependencies
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{proxy}}"
      package:
        name: "{{ item }}"
        state: present
      loop:
        - java-21-openjdk-devel
        - wget
        - tar
        - python3-libsemanage
        - policycoreutils-python-utils

    - name: Ensure each sysctl setting is present in sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        regexp: "^{{ item.key }}\\s*="
        line: "{{ item.key }} = {{ item.value }}"
        state: present
      loop: "{{ sysctl_settings }}"

    - name: Set Transparent Huge Pages to 'never'
      shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled
      register: thp_result
      ignore_errors: true
      changed_when: thp_result.rc == 0

    - name: Append limits for redis in /etc/security/limits.conf
      lineinfile:
        path: /etc/security/limits.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        insertafter: EOF
      with_items:
        - { regexp: '^redis\s+soft\s+nofile\s+65536', line: 'redis              soft    nofile  65536' }
        - { regexp: '^redis\s+hard\s+nofile\s+65536', line: 'redis              hard    nofile  65536' }
        - { regexp: '^redis\s+soft\s+nproc\s+unlimited', line: 'redis              soft    nproc   unlimited' }
        - { regexp: '^redis\s+hard\s+nproc\s+unlimited', line: 'redis              hard    nproc   unlimited' }

    - name: Apply sysctl settings
      shell: sudo sysctl -p
      
    - name: Configure dnf to use proxy
      lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: "^proxy="
        line: "proxy={{ proxy }}"
        state: present

    - name: Module Reset Redis 
      shell: sudo dnf -y module reset redis
      
    - name: Module Check Redis 
      shell: sudo dnf module list redis

    - name: Install Redis 
      #shell: sudo dnf module -y install redis
      shell: sudo dnf module -y install redis:remi-7.2

    #Default Configration
    - name: Set bind config in redis.conf
      lineinfile:
        path: "{{redis_config_path}}/redis.conf"
        regexp: '^bind 127.0.0.1 -::1'
        line: 'bind *'
        create: yes
        owner: "{{ redis_user }}"
        group: "{{ redis_group }}"
        mode: '0755'

    - name: Set protected-mode config in redis.conf
      lineinfile:
        path: "{{redis_config_path}}/redis.conf"
        regexp: '^protected-mode'
        line: 'protected-mode no'
        create: yes
        owner: "{{ redis_user }}"
        group: "{{ redis_group }}"
        mode: '0755'

    #Clustering Configration
    - name: Set cluster-enabled config in redis.conf
      lineinfile:
        path: "{{redis_config_path}}/redis.conf"
        regexp: '^cluster-enabled'
        line: 'cluster-enabled yes'
        create: yes
        owner: "{{ redis_user }}"
        group: "{{ redis_group }}"
        mode: '0755'

    - name: Set cluster-config-file config in redis.conf
      lineinfile:
        path: "{{redis_config_path}}/redis.conf"
        regexp: '^cluster-config-file'
        line: 'cluster-config-file nodes-6379.conf'
        create: yes
        owner: "{{ redis_user }}"
        group: "{{ redis_group }}"
        mode: '0755'

    - name: Set cluster-node-timeout config in redis.conf
      lineinfile:
        path: "{{redis_config_path}}/redis.conf"
        regexp: '^cluster-node-timeout'
        line: 'cluster-node-timeout 5000'
        create: yes
        owner: "{{ redis_user }}"
        group: "{{ redis_group }}"
        mode: '0755'

    - name: Install Redis 
      shell: sudo systemctl enable --now redis
      
    - name: Configure Redis Sentinel
      copy:
        dest: "{{redis_config_path}}/sentinel1.conf"
        content: |
          port 26379
          dir "/tmp"
          sentinel monitor mymaster {{ ansible_host }} 6379 2
          sentinel down-after-milliseconds mymaster 500
          sentinel failover-timeout mymaster 1000
          sentinel parallel-syncs mymaster 1
        owner: "{{ redis_user }}"
        group: "{{ redis_group }}"
        mode: '0755'
          
    - name: Create systemd service file for Redis Sentinel1
      copy:
        dest: /etc/systemd/system/redis-sentinel1.service
        content: |
          [Unit]
          Description=Redis Sentinel
          After=network.target

          [Service]
          ExecStart=/bin/redis-server {{redis_config_path}}sentinel.conf --sentinel
          #ExecStart=/bin/redis-server {{redis_config_path}}sentinel.conf --sentinel 1>/dev/null 2>&1 &
          ExecStop=/bin/kill -s TERM $MAINPID
          Restart=always
          User=redis
          Group=redis

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Redis Sentinel service
      systemd:
        name: redis-sentinel1
        state: restarted
        enabled: yes
