---
- hosts: solr
  become: yes
  vars:
    solr_version: "9.8.1"
    solr_home: "/opt"
    solr_user: "user"
    solr_group: "user"
    solr_port_base: 8983
    proxy: "http://xxx.xxx.xxx.xxx0:3128/"
    solr_heap: "3g" #solr heap size 정의
    zk_group: zk #클러스터링 zookeeper 인벤토리 그룹 지정/

  tasks:
    # Config limit.conf in system
    - name: Configure system limits for {{ username }}
      lineinfile:
        path: /etc/security/limits.conf
        state: present
        create: yes
        line: "{{ item }}"
      with_items:
        - "{{ solr_user }} soft nofile 65536"
        - "{{ solr_user }} hard nofile 65536"
        - "{{ solr_user }} soft nproc unlimited"
        - "{{ solr_user }} hard nproc unlimited"
      vars:
        username: solr

    - name: Stop and disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Install necessary dependencies
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{proxy}}"
      package:
        name: "{{ item }}"
        state: present
      loop:
        - java-21-openjdk-devel
        - wget
        - tar
        - unzip
        - gzip

    - name: Download Solr
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{proxy}}"
      get_url:
        url: "https://archive.apache.org/dist/solr/solr/{{solr_version}}/solr-{{solr_version}}.tgz"
        dest: /tmp/solr-{{solr_version}}.tgz
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"

    - name: Create solr directory
      file:
        path: "{{ solr_home }}"
        state: directory
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"
        mode: '0755'

    - name: Extract solr
      become: yes
      unarchive:
        src: "/tmp/solr-{{solr_version}}.tgz"
        dest: "{{ solr_home }}"
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"
        mode: '0755'
        remote_src: yes

    # config solr heap size & zookeeper node in solr.in.sh
    - name: 'Set SOLR_HEAP in solr.in.sh(default: #SOLR_HEAP="512m")'
      lineinfile:
        path: "{{ solr_home }}/solr-{{ solr_version }}/bin/solr.in.sh"
        regexp: '^#SOLR_HEAP='
        line: 'SOLR_HEAP="{{solr_heap}}"'
        create: yes
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"
        mode: '0755'

    - name: 'Set SOLR_HOST in solr.in.sh(default: #SOLR_HOST="192.168.1.1" )'
      lineinfile:
        path: "{{ solr_home }}/solr-{{ solr_version }}/bin/solr.in.sh"
        regexp: '^#SOLR_HOST='
        line: 'SOLR_HOST={{ansible_host}}'
        create: yes
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"
        mode: '0755'  

    - name: 'Set ZK_HOST in solr.in.sh(default: #ZK_HOST="" )'
      lineinfile:
        path: "{{ solr_home }}/solr-{{ solr_version }}/bin/solr.in.sh"
        regexp: '^#ZK_HOST='
        line: "ZK_HOST={{ groups[zk_group] | join(':2181,') }}:2181"
        create: yes
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"
        mode: '0755'

    - name: 'Set SORL_JETTY_HOST in solr.in.sh(default:#SOLR_JETTY_HOST="127.0.0.1" )'
      lineinfile:
        path: "{{ solr_home }}/solr-{{ solr_version }}/bin/solr.in.sh"
        regexp: '^#SOLR_JETTY_HOST='
        line: 'SOLR_JETTY_HOST=0.0.0.0'
        create: yes
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"
        mode: '0755'          

    - name: Create a symbolic link from /opt/solr to actual solr directory
      file:
        src: "{{ solr_home }}/solr-{{ solr_version }}"
        dest: "{{ solr_home }}/solr"
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"
        state: link
      
    - name: Change ownership of the symbolic link to solr_user and solr_group
      command: chown -h {{ solr_user }}:{{ solr_group }} "{{ solr_home }}/solr"
      
