---
- name: Install and start ZooKeeper
  hosts: zk
  become: true
  vars:
    zookeeper_version: "X.X.X"
    zookeeper_home: "/opt"
    zookeeper_user: "qubit"
    zookeeper_group: "qubit"
    zookeeper_ip: "{{ ansible_host }}"
    proxy: "http://172.16.10.20:3128/"
    
  tasks:
    - name: Stop and disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no
        
    - name: Install necessary dependencies
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{proxy}}"
      package:
        name: "{{ item }}"
        state: present
      loop:
        - libXft
        - java-21-openjdk-devel
        - wget
        - tar

    - name: Download ZooKeeper
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{proxy}}"
      get_url:
        url: https://dlcdn.apache.org/zookeeper/zookeeper-{{zookeeper_version}}/apache-zookeeper-{{zookeeper_version}}-bin.tar.gz
        dest: /tmp/apache-zookeeper-{{zookeeper_version}}-bin.tar.gz
        owner: "{{ zookeeper_user }}"
        group: "{{ zookeeper_group }}"

    - name: Create zookeeper directory
      file:
        path: "{{ zookeeper_home }}"
        state: directory
        owner: qubit
        group: qubit
        mode: '0755'
     
    - name: Extract ZooKeeper for zookeeper
      unarchive:
        src: "/tmp/apache-zookeeper-{{zookeeper_version}}-bin.tar.gz"
        dest: "{{ zookeeper_home }}"
        owner: "{{ zookeeper_user }}"
        group: "{{ zookeeper_group }}"
        mode: '0755'
        remote_src: yes

    - name: Create ZooKeeper data directory for zookeeper
      file:
        path: "{{ zookeeper_home }}/apache-zookeeper-{{zookeeper_version}}-bin/data"
        state: directory
        owner: qubit
        group: qubit
        mode: '0755'

    - name: Create myid file for zookeeper
      copy:
        dest: "{{ zookeeper_home }}/apache-zookeeper-{{zookeeper_version}}-bin/data/myid"
        content: "{{ groups['zk'].index(inventory_hostname) + 1 }}"
        owner: "{{ zookeeper_user }}"
        group: "{{ zookeeper_group }}"
        mode: '0644'

    - name: Configure zookeeper properties
      template:
        src: zoo.cfg.j2
        dest: "/opt/apache-zookeeper-{{zookeeper_version}}-bin/conf/zoo.cfg"
        owner: qubit
        group: qubit
        mode: '0644'
        
    - name: Start ZooKeeper for zookeeper
      command: "{{ zookeeper_home }}/apache-zookeeper-{{zookeeper_version}}-bin/bin/zkServer.sh start {{ zookeeper_home }}/apache-zookeeper-X.X.X-bin/conf/zoo.cfg"
      become: true
      become_user: "{{ zookeeper_user }}"
      register: zookeeper_start

