---
- name: Install and start ZooKeeper
  hosts: zk
  become: true
  vars:
    kafka_version_major: "2.12-"
    kafka_version_minor: "3.8.0"
    zookeeper_version: "3.8.4"
    zookeeper_home: "/opt"
    zookeeper_user: "qubit"
    zookeeper_group: "qubit"
    zookeeper_ip: "{{ ansible_host }}"
  tasks:
    - name: Stop and disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no
        
    - name: Install necessary dependencies
      environment:
        http_proxy: "http://172.16.10.20:3128/"
        https_proxy: "http://172.16.10.20:3128/"
      package:
        name: "{{ item }}"
        state: present
      loop:
        - libXft
        - java-21-openjdk-devel
        - wget
        - tar

    - name: Download ZooKeeper
      environment:
        http_proxy: "http://172.16.10.20:3128/"
        https_proxy: "http://172.16.10.20:3128/"
      get_url:
        url: https://dlcdn.apache.org/zookeeper/zookeeper-{{zookeeper_version}}/apache-zookeeper-{{zookeeper_version}}-bin.tar.gz
        dest: /tmp/apache-zookeeper-{{zookeeper_version}}-bin.tar.gz
        owner: "{{ zookeeper_user }}"
        group: "{{ zookeeper_group }}"

#    - name: Extract ZooKeeper
#      unarchive:
#        src: /tmp/apache-zookeeper-3.8.4-bin.tar.gz
#        dest: /opt/
#        remote_src: yes

    - name: Create zookeeper directory
      file:
        path: "{{ zookeeper_home }}"
        state: directory
        owner: qubit
        group: qubit
        mode: '0755'
     
    - name: Extract ZooKeeper for zookeeper
      unarchive:
        src: "/tmp/apache-zookeeper-{{zookeeper_version}}-bin.tar.gz"
        dest: "{{ zookeeper_home }}"
        owner: "{{ zookeeper_user }}"
        group: "{{ zookeeper_group }}"
        mode: '0755'
        remote_src: yes

#    - name: Copy ZooKeeper configuration
#      copy:
#        src: /opt/apache-zookeeper-3.8.4-bin/conf/zoo_sample.cfg
#        dest: /opt/apache-zookeeper-3.8.4-bin/conf/zoo.cfg




#    - name: Modify ZooKeeper configuration
#      lineinfile:
#        path: /opt/apache-zookeeper-3.8.4-bin/conf/zoo.cfg
#        regexp: '^dataDir='
#        line: 'dataDir=/var/lib/zookeeper'

    - name: Create ZooKeeper data directory for zookeeper
      file:
        path: "{{ zookeeper_home }}/apache-zookeeper-{{zookeeper_version}}-bin/data"
        state: directory
        owner: qubit
        group: qubit
        mode: '0755'

#    - name: Configure zookeeper properties
#      template:
#        src: zoo.cfg
#        dest: /opt/apache-zookeeper-3.8.4-bin/conf/zoo.cfg
#
 
    - name: Create myid file for zookeeper
      copy:
        dest: "{{ zookeeper_home }}/apache-zookeeper-{{zookeeper_version}}-bin/data/myid"
        content: "{{ groups['zk'].index(inventory_hostname) + 1 }}"
        owner: "{{ zookeeper_user }}"
        group: "{{ zookeeper_group }}"
        mode: '0644'


        
    # - name: Configure zookeeper properties
      # copy:
        # dest: "{{ zookeeper_home }}/apache-zookeeper-3.8.4-bin/conf/zoo.cfg"
        # content: |
            # tickTime=4000
            # initLimit=10
            # syncLimit=5
            # dataDir={{ zookeeper_home }}/apache-zookeeper-3.8.4-bin/data
            # dataLogDir={{ zookeeper_home }}/apache-zookeeper-3.8.4-bin/logs
            # clientPort=2181
            # admin.serverPort=8081
            # autopurge.snapRetainCount=6
            # autopurge.purgeInterval=48
            # 4lw.commands.whitelist=mntr,conf,ruok,srvr
            # server.1={{ zookeeper_ip }}:2887:3887:participant;2181
            # server.2={{ zookeeper_ip }}:2888:3888:participant;2182
            # server.3={{ zookeeper_ip }}:2889:3889:participant;2183
        # owner: qubit
        # group: qubit
        # mode: '0755'
    
    - name: Configure zookeeper properties
      template:
        src: zoo.cfg.j2
        dest: "/opt/apache-zookeeper-{{zookeeper_version}}-bin/conf/zoo.cfg"
        owner: qubit
        group: qubit
        mode: '0644'
        
    - name: Start ZooKeeper for zookeeper
      command: "{{ zookeeper_home }}/apache-zookeeper-{{zookeeper_version}}-bin/bin/zkServer.sh start {{ zookeeper_home }}/apache-zookeeper-3.8.4-bin/conf/zoo.cfg"
      become: true
      become_user: "{{ zookeeper_user }}"
      register: zookeeper_start

